spring:
  datasource:     # 配置数据源信息
    dynamic:
      primary: master     # 设置默认的数据源或者数据源组,默认值即为master
      strict: false       # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:4406/mybatis_plus?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456789
        slave_1:
          url: jdbc:mysql://localhost:4406/mybatis_plus_1?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456789
